# Generated by Django 5.1.1 on 2024-11-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='color',
            new_name='color_animal',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='specie',
            new_name='specie_animal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_user',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('number_document', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='app_create_account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_job', models.CharField(blank=True, max_length=50, null=True)),
                ('position_job', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_job', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app_create_account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('model_vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('year_vehicle', models.IntegerField(blank=True, null=True)),
                ('color_vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='app_create_account.user')),
            ],
        ),
    ]
